---

- name: "Obtaining percona public key"
  apt_key:
    url: "http://www.percona.com/downloads/RPM-GPG-KEY-percona"
    state: "present"

- name: "Adding percona repository"
  apt_repository:
    repo: "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state: "present"
  when: "ansible_distribution_release != 'xenial'"

- name: "Adding percona repository (use wily packages as xenial package N/A yet)"
  apt_repository:
    repo: "deb http://repo.percona.com/apt wily main"
    state: "present"
  when: "ansible_distribution_release == 'xenial'"

- name: "Update apt cache"
  apt:
    update_cache: "yes"
    cache_valid_time: "300"

- name: "Install percona client"
  apt:
    pkg: "percona-server-client-5.5"
    state: "latest"
